env:
	cd ../ && source oss-cad-suite/environment

# Plusarg da passare a vvp. Quelli che capisce il tb:
#   +nodump              niente VCD (obbligatorio sulle netlist, il dump e' GB)
#   +gatedump            VCD ridotto ai segnali del clock gating (clkgen + top)
#   +runtime_ns=N        durata simulata dopo il rilascio dei bottoni (dflt 9 ms)
#   +window=N            quale occorrenza di idle/inferenza va nel riepilogo
#
# Per le finestre di potenza servono piu' di 9 ms: il caricamento di pesi e
# istruzioni via SPI si prende da solo i primi ~6.3 ms.
#   make simulate SIMFLAGS="+runtime_ns=25000000"
SIMFLAGS ?=

simulate:
	cd firmware && make -B
	python3 scripts/gen_rom_boot.py                 # ROM di boot dal firmware fresco
	python3 scripts/build_flash_asic.py emg         # flash ASIC (campioni+pesi+delta+firmware)
	# -DOPENROAD_CLKGATE non serve piu': il gate e' rtl/servant/syntzulu_icg.v,
	# che sceglie il modello comportamentale sul -DFUNCTIONAL che c'e' gia'.
	# Per disattivare il gating in sim: iverilog ... -DNO_CLKGATE
	iverilog -DFUNCTIONAL -o rtl_sim  rtl/define.v sim/tb/servant_tb_mnist.v sim/tb/servant_sim.v sim/tb/uart_decoder.v sim/tb/vlog_tb_utils.v sim/tb/flash_spi_sim.sv rtl/servant/* rtl/serv/* rtl/syntzulu/* rtl/memorie_ihp/* rtl/behavioural_ihp/* std_cells/*
	vvp rtl_sim $(SIMFLAGS)
	rm rtl_sim
	mv tb_serv.vcd work/
	gtkwave --save=work/serv_waves.gtkw work/tb_serv.vcd &


# ------------------------------------------------------------------
#  Setup del flow ASIC (OpenROAD / IHP SG13G2)
#
#      make setup_orfs
#
#  1. genera orfs_setup/paths.mk (RTL_ROOT assoluto: l'unico pezzo
#     dipendente dalla macchina, per questo non va committato)
#  2. crea il symlink designs/$(PLATFORM)/SYNtzulu-Conv -> orfs_setup/
#     dentro ORFS, come config_soc.mk si aspetta
#
#  Poi la sintesi del soc si lancia con:
#      cd $(OPENROAD_PATH)/flow && \
#      make DESIGN_CONFIG=./designs/$(PLATFORM)/SYNtzulu-Conv/soc/config_soc.mk synth
# ------------------------------------------------------------------
OPENROAD_PATH ?= /home/luca/OpenROAD-flow-scripts_new
PLATFORM      ?= ihp-sg13g2

.PHONY: setup_orfs
setup_orfs:
	@printf '%s\n%s\n%s\n' \
	  '# GENERATED by "make setup_orfs" - do not edit, do not commit.' \
	  '# Absolute path of this repo, the only machine dependent piece of the flow.' \
	  'RTL_ROOT := $(CURDIR)/rtl' > orfs_setup/paths.mk
	ln -sfn $(CURDIR)/orfs_setup $(OPENROAD_PATH)/flow/designs/$(PLATFORM)/SYNtzulu-Conv
	@echo "ok: paths.mk generato, symlink creato."
	@echo "sintesi soc:  cd $(OPENROAD_PATH)/flow && make DESIGN_CONFIG=./designs/$(PLATFORM)/SYNtzulu-Conv/soc/config_soc.mk synth"


	

# ------------------------------------------------------------------
#  VARIANTE DEL FLOW ORFS - nessun default, di proposito.
#
#  Le netlist qui sotto vivono in .../SYNtzulu_Conv/<VARIANT>/, e VARIANT va
#  scelta a mano ogni volta. Un default e' esattamente la trappola in cui si
#  cade: simulare la netlist di una variante vecchia non da' nessun errore,
#  parte e produce risultati sbagliati. E' gia' successo con un default che
#  puntava alla variante 1, sintetizzata sei giorni prima del firmware con cui
#  la si stava simulando: la UART sputava X e la causa non era evidente.
#
#      make simulate_post_syn    VARIANT=5
#      make simulate_post_layout VARIANT=5
#      make genus_power          VARIANT=5
#
#  Chi vuole una netlist fuori da ORFS scavalca il path completo e VARIANT non
#  serve:
#      make simulate_post_syn SOC_NETLIST=<path>
# ------------------------------------------------------------------
ORFS_RESULTS ?= /home/luca/OpenROAD-flow-scripts_new/flow/results/ihp-sg13g2/SYNtzulu_Conv
VARIANT      ?=

# Ferma il target se VARIANT non e' stata data o se la netlist non esiste.
# $(1) e' la netlist attesa. Il controllo sta nella ricetta e non nel corpo del
# Makefile: un $(error) a livello di parsing farebbe fallire ANCHE i target che
# con la variante non c'entrano niente, "simulate" per primo.
define require_variant
	@if [ -z "$(VARIANT)" ]; then \
	  echo ""; \
	  echo "ERRORE: VARIANT non impostata - va scelta a mano, non c'e' un default."; \
	  echo ""; \
	  echo "    make $@ VARIANT=<n>"; \
	  echo ""; \
	  echo "  varianti disponibili in $(ORFS_RESULTS):"; \
	  ls -1 $(ORFS_RESULTS) 2>/dev/null | sed 's/^/      /' || echo "      (nessuna)"; \
	  echo ""; \
	  exit 1; \
	fi
	@if [ ! -f "$(1)" ]; then \
	  echo ""; \
	  echo "ERRORE: $(1) non esiste."; \
	  echo "  La variante $(VARIANT) non e' arrivata a questo stadio del flow."; \
	  echo ""; \
	  exit 1; \
	fi
endef

# Simulazione post-sintesi del soc: stessi testbench di "simulate", ma al posto
# dell'RTL (servant/serv/syntzulu/memorie_ihp) si legge la netlist gate-level
# prodotta da ORFS. Servono ancora: define.v (define EMG/CONFIG_PATH usati dai
# tb), i modelli comportamentali delle macro RAM (nella netlist sono blackbox)
# e le std cell / IO IHP.
#   make simulate_post_syn VARIANT=<n>
#   make simulate_post_syn SOC_NETLIST=<altra netlist>
SOC_NETLIST ?= $(ORFS_RESULTS)/$(VARIANT)/1_synth.v

simulate_post_syn:
	$(call require_variant,$(SOC_NETLIST))
	cd firmware && make -B
	python3 scripts/gen_rom_boot.py                 # ROM di boot dal firmware fresco
	python3 scripts/build_flash_asic.py emg         # flash ASIC (campioni+pesi+delta+firmware)
	iverilog -DFUNCTIONAL -DPSIM -o post_syn_sim  rtl/define.v sim/tb/servant_tb_mnist.v sim/tb/servant_sim.v sim/tb/uart_decoder.v sim/tb/vlog_tb_utils.v sim/tb/flash_spi_sim.sv $(SOC_NETLIST) rtl/behavioural_ihp/* std_cells/*
	vvp post_syn_sim $(SIMFLAGS)
	rm post_syn_sim
	mv ps_tb_serv.vcd work/
	gtkwave --save=work/serv_waves.gtkw work/ps_tb_serv.vcd &

# Simulazione post-layout del soc: identica a "simulate_post_syn", ma la netlist
# e' quella finale scritta da ORFS dopo detailed route/fill (6_final.v), quindi
# include anche tapcell/fill/antenna diode e i buffer di CTS.
#   make simulate_post_layout VARIANT=<n>
#   make simulate_post_layout SOC_NETLIST_PL=<altra netlist>
SOC_NETLIST_PL ?= $(ORFS_RESULTS)/$(VARIANT)/6_final.v

simulate_post_layout:
	$(call require_variant,$(SOC_NETLIST_PL))
	cd firmware && make -B
	python3 scripts/gen_rom_boot.py                 # ROM di boot dal firmware fresco
	python3 scripts/build_flash_asic.py emg         # flash ASIC (campioni+pesi+delta+firmware)
	iverilog -DFUNCTIONAL -DPSIM -o post_layout_sim  rtl/define.v sim/tb/servant_tb_mnist.v sim/tb/servant_sim.v sim/tb/uart_decoder.v sim/tb/vlog_tb_utils.v sim/tb/flash_spi_sim.sv sim/tb/nettype_wire.v $(SOC_NETLIST_PL) rtl/behavioural_ihp/* std_cells/*
	vvp post_layout_sim $(SIMFLAGS)
	rm post_layout_sim
	mv ps_tb_serv.vcd work/pl_tb_serv.vcd
	@mv -f sim/results/emg/power_windows_ps.txt sim/results/emg/power_windows_pl.txt 2>/dev/null || true
	gtkwave --save=work/serv_waves.gtkw work/pl_tb_serv.vcd &

.PHONY: sim_post_layout
sim_post_layout: simulate_post_layout

# ------------------------------------------------------------------
#  Pacchetto per la stima di potenza con Genus
#
#      make genus_power VARIANT=5
#      make genus_power VARIANT=3 CORNER=slow
#      make genus_power VARIANT=5 GENUS_ARGS=--no-zip
#
#  Mette in work/genus_power_<app>_v<variante>.zip due script Genus (una
#  finestra di idle e una di inferenza), la netlist post-layout con .sdc e
#  .spef, i .lib del corner e il VCD della post-layout.
#
#  Prerequisiti, entrambi prodotti da "make simulate_post_layout":
#    - work/pl_tb_serv.vcd                        quindi SENZA +nodump
#    - sim/results/<app>/power_windows_pl.txt     da cui vengono gli istanti
#
#  Il VCD pesa qualche GB, lo zip ci mette qualche minuto.
# ------------------------------------------------------------------
CORNER     ?= typ
GENUS_ARGS ?=

.PHONY: genus_power
genus_power:
	$(call require_variant,$(ORFS_RESULTS)/$(VARIANT)/6_final.v)
	python3 scripts/gen_genus_power.py --variant $(VARIANT) --corner $(CORNER) $(GENUS_ARGS)

listen:
	sudo rm -f output/serial.txt || true
	sudo minicom -b 4000000 -H -C output/serial.txt -D /dev/ttyUSB1

create_application:
	@if [ -z "$(app)" ]; then \
		echo "Usage: make create_application app=<application_name>"; \
		exit 1; \
	fi
	mkdir -p rtl/config/$(app) sim/mem/$(app) sim/target/$(app) sim/results/$(app);\
	cp $(app)/config.txt rtl/config/$(app)/; \
	cp $(app)/delta.txt sim/mem/$(app)/; \
	cp $(app)/flash.txt sim/mem/$(app)/; \
	cp $(app)/encoded_input.txt sim/target/$(app)/; \
	cp $(app)/snn_inference.txt sim/target/$(app)/; \
	#cp $(app)/spike_1.txt sim/target/$(app)/
	mkdir firmware/src/applications/$(app)/
	cp $(app)/*.h firmware/src/applications/$(app)/
	cd firmware && make -B compile app=$(app)
	mkdir flash/src/$(app)/
	cp $(app)/weights_1.hex $(app)/weights_2.hex $(app)/weights_3.hex $(app)/weights_4.hex $(app)/address.txt $(app)/samples.txt $(app)/instruction.hex flash/src/$(app)/
	
create_application_BRAM:
	@if [ -z "$(app)" ]; then \
		echo "Usage: make create_application app=<application_name>"; \
		exit 1; \
	fi
	mkdir -p rtl/config/$(app) sim/mem/$(app) sim/target/$(app) sim/results/$(app);\
	cp $(app)/config.txt rtl/config/$(app)/; \
	cp $(app)/delta_concat.hex sim/mem/$(app)/; \
	python3 scripts/build_flash_asic.py $(app); \
	cp $(app)/spike_vec.txt sim/target/$(app)/; \
	cp $(app)/snn_inference.txt sim/target/$(app)/; \
	#cp $(app)/spike_1.txt sim/target/$(app)/
	mkdir firmware/src/applications/$(app)/
	cp $(app)/*.h firmware/src/applications/$(app)/
	cd firmware && make -B compile app=$(app)
	mkdir flash/src/$(app)/
	cp $(app)/weights_1_1.hex $(app)/weights_1_2.hex $(app)/weights_1_3.hex $(app)/weights_2_1.hex $(app)/weights_2_2.hex $(app)/weights_2_3.hex $(app)/weights_3_1.hex $(app)/weights_3_2.hex $(app)/weights_3_3.hex $(app)/weights_4_1.hex $(app)/weights_4_2.hex $(app)/weights_4_3.hex $(app)/samples.txt $(app)/instruction.hex $(app)/address.txt flash/src/$(app)/
	
clean_application:
	@if [ -z "$(app)" ]; then \
		echo "Usage: make clean_application app=<application_name>"; \
		exit 1; \
	fi
	rm -r rtl/config/$(app)/; \
	rm -r sim/mem/$(app)/; \
	rm -r sim/target/$(app)/; \
	rm -r sim/results/$(app)/; \
	rm -r firmware/src/applications/$(app)/; \
	rm -r flash/src/$(app)/; \

clean_all_applications:
	rm -f *.vcd 
	rm -f rtl_sim
	rm -f gate_sim
	rm -r rtl/config/*; \
	rm -r sim/mem/*; \
	rm -r sim/target/*; \
	rm -r sim/results/*; \
	rm -r firmware/src/applications/*; \
	rm -r flash/src/*; \
	rm -r flash/from_flash/*; \
	rm -r flash/to_flash/*; \
	rm -r output/*

clean:
	rm -f *.vcd 
	rm -f rtl_sim
	rm -f gate_sim
	rm -f work/*.vcd
