#define WEIGHT_DEPTH 8192
#define CHANNELS 256
#define TIME 0
#define WEIGHT_1_ADDR 1048576
#define WEIGHT_2_ADDR WEIGHT_1_ADDR+WEIGHT_DEPTH
#define WEIGHT_3_ADDR WEIGHT_2_ADDR+WEIGHT_DEPTH
#define WEIGHT_4_ADDR WEIGHT_3_ADDR+WEIGHT_DEPTH
#define SAMPLE_ADDR   WEIGHT_4_ADDR+WEIGHT_DEPTH
